# Codemagic YAML configuration for Clima Predict Flutter App
# More info: https://docs.codemagic.io/yaml/building-yaml

workflows:
  # Android Workflow
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      # Uncomment and add your environment variable groups when ready:
      # groups:
      #   - keystore_credentials
      #   - api_keys
      vars:
        PACKAGE_NAME: "com.climapredict.app.clima_predict"
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter Analyze
        script: |
          flutter analyze
      - name: Test
        script: |
          flutter test
      - name: Build APK
        script: |
          flutter build apk --release
      - name: Build App Bundle
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - yasar.khan.cg@gmail.com
        notify:
          success: true
          failure: false
      # Uncomment and configure when ready
      # app_store:
      #   auth:
      #     iss: "YOUR_APP_STORE_CONNECT_ISSUER_ID"
      #     kid: "YOUR_APP_STORE_CONNECT_KEY_IDENTIFIER"
      #   beta:
      #     expires: "not_available"
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal

  # Web Workflow (Optional)
  web-workflow:
    name: Web Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Flutter Analyze
        script: |
          flutter analyze
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - yasar.khan.cg@gmail.com
        notify:
          success: true
          failure: false

