import 'package:hive_flutter/hive_flutter.dart';
import 'package:flutter/foundation.dart';
import '../models/farmer_profile.dart';
import '../models/forecast_cache.dart';
import '../models/sensor_reading.dart';
import '../models/feedback.dart';
import '../models/insurance_claim.dart';

class DatabaseService {
  static const String farmerProfileBox = 'farmer_profile';
  static const String forecastCacheBox = 'forecast_cache';
  static const String sensorReadingBox = 'sensor_readings';
  static const String feedbackBox = 'feedback';
  static const String insuranceClaimBox = 'insurance_claims';

  static Future<void> init() async {
    try {
      await Hive.initFlutter();
      
      // Register adapters (generated by build_runner)
      // Safe to call multiple times; Hive ignores duplicates
      // If adapters not generated, boxes will still open but won't persist custom objects
      if (!Hive.isAdapterRegistered(0)) {
        try {
          Hive.registerAdapter(FarmerProfileAdapter());
        } catch (e) {
          debugPrint('FarmerProfileAdapter not available: $e');
        }
      }
      if (!Hive.isAdapterRegistered(1)) {
        try {
          Hive.registerAdapter(ForecastCacheAdapter());
        } catch (e) {
          debugPrint('ForecastCacheAdapter not available: $e');
        }
      }
      if (!Hive.isAdapterRegistered(2)) {
        try {
          Hive.registerAdapter(DailyForecastAdapter());
        } catch (e) {
          debugPrint('DailyForecastAdapter not available: $e');
        }
      }
      if (!Hive.isAdapterRegistered(3)) {
        try {
          Hive.registerAdapter(SensorReadingAdapter());
        } catch (e) {
          debugPrint('SensorReadingAdapter not available: $e');
        }
      }
      if (!Hive.isAdapterRegistered(4)) {
        try {
          Hive.registerAdapter(FeedbackAdapter());
        } catch (e) {
          debugPrint('FeedbackAdapter not available: $e');
        }
      }
      if (!Hive.isAdapterRegistered(5)) {
        try {
          Hive.registerAdapter(InsuranceClaimEstimateAdapter());
        } catch (e) {
          debugPrint('InsuranceClaimEstimateAdapter not available: $e');
        }
      }

      // Open boxes
      await Hive.openBox(farmerProfileBox);
      await Hive.openBox(forecastCacheBox);
      await Hive.openBox(sensorReadingBox);
      await Hive.openBox(feedbackBox);
      await Hive.openBox(insuranceClaimBox);
      
      debugPrint('Hive initialized successfully');
    } catch (e) {
      debugPrint('Error initializing Hive: $e');
      rethrow;
    }
  }

  // Farmer Profile
  static Future<void> saveFarmerProfile(FarmerProfile profile) async {
    final box = Hive.box(farmerProfileBox);
    await box.put('current_profile', profile);
  }

  static FarmerProfile? getFarmerProfile() {
    try {
      if (!Hive.isBoxOpen(farmerProfileBox)) return null;
      final box = Hive.box(farmerProfileBox);
      return box.get('current_profile') as FarmerProfile?;
    } catch (e) {
      debugPrint('Error getting farmer profile: $e');
      return null;
    }
  }

  // Forecast Cache
  static Future<void> saveForecastCache(ForecastCache forecast) async {
    final box = Hive.box(forecastCacheBox);
    await box.put(forecast.id, forecast);
  }

  static ForecastCache? getForecastCache(String id) {
    final box = Hive.box(forecastCacheBox);
    return box.get(id) as ForecastCache?;
  }

  static List<ForecastCache> getAllForecasts() {
    final box = Hive.box(forecastCacheBox);
    return box.values.cast<ForecastCache>().toList();
  }

  static ForecastCache? getLatestForecastForVillage(String village) {
    final forecasts = getAllForecasts()
        .where((f) => f.village == village)
        .toList();
    if (forecasts.isEmpty) return null;
    forecasts.sort((a, b) => b.generatedAt.compareTo(a.generatedAt));
    return forecasts.first;
  }

  // Sensor Readings
  static Future<void> saveSensorReading(SensorReading reading) async {
    final box = Hive.box(sensorReadingBox);
    final key = '${reading.sensorId}_${reading.timestamp.millisecondsSinceEpoch}';
    await box.put(key, reading);
  }

  static List<SensorReading> getSensorReadings(
    String village, {
    DateTime? startDate,
    DateTime? endDate,
  }) {
    final box = Hive.box(sensorReadingBox);
    final allReadings = box.values.cast<SensorReading>().toList();
    
    var filtered = allReadings.where((r) => r.village == village);
    
    if (startDate != null) {
      filtered = filtered.where((r) => r.timestamp.isAfter(startDate));
    }
    if (endDate != null) {
      filtered = filtered.where((r) => r.timestamp.isBefore(endDate));
    }
    
    filtered.toList().sort((a, b) => b.timestamp.compareTo(a.timestamp));
    return filtered.toList();
  }

  // Feedback
  static Future<void> saveFeedback(Feedback feedback) async {
    final box = Hive.box(feedbackBox);
    await box.put(feedback.id, feedback);
  }

  static List<Feedback> getPendingFeedbacks() {
    final box = Hive.box(feedbackBox);
    // In real implementation, filter by sync status
    return box.values.cast<Feedback>().toList();
  }

  // Insurance Claims
  static Future<void> saveInsuranceClaim(InsuranceClaimEstimate claim) async {
    final box = Hive.box(insuranceClaimBox);
    await box.put(claim.recordId, claim);
  }

  static InsuranceClaimEstimate? getInsuranceClaim(String recordId) {
    final box = Hive.box(insuranceClaimBox);
    return box.get(recordId) as InsuranceClaimEstimate?;
  }

  static List<InsuranceClaimEstimate> getAllInsuranceClaims() {
    final box = Hive.box(insuranceClaimBox);
    return box.values.cast<InsuranceClaimEstimate>().toList();
  }

  static Future<void> clearAll() async {
    await Hive.deleteFromDisk();
    await init();
  }
}

